[connections.snowflake]
account = "TDESBPE-UU05589"
user = "StuBecker124"
password = "5+*4AfdW6,NeD65"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true